
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class AdminGetDetails extends javax.swing.JFrame {
    ArrayList<Cart> al;
    /**
     * Creates new form AdminGetDetails
     */
    public AdminGetDetails(ArrayList<Cart> al) {
        initComponents();
        
        this.al = al;
        
        setSize(800,500);
        setLocationRelativeTo(null);
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setText("FILL DETAILS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 40, 250, 90);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("CUSTOMER PHONE NUMBER : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 200, 300, 40);

        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        getContentPane().add(tf1);
        tf1.setBounds(290, 200, 280, 40);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("MODE OF PAYMENT :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 280, 260, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "CREDIT CARD", "DEBIT CARD", "UPI" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(290, 270, 280, 40);

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jButton1.setText("DO PAYMENT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(160, 330, 150, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String phoneno =tf1.getText();
        String adminemail = Global.adminemail;
        int gtotal = Global.gtotal;
        String paymenttype = (String) jComboBox1.getSelectedItem();
        int billid = 0;
        
        
        
         try{
            ResultSet rs = DBLoader.executeQuery("select * from bill");
    
                    rs.moveToInsertRow();
                                
            rs.updateInt("gtotal",gtotal);
            rs.updateString("adminemail",adminemail);
            rs.updateString("phoneno",phoneno);
            rs.updateString("paymenttype",paymenttype);
            
        
            rs.insertRow();
            
            
             ResultSet rs2 = DBLoader.executeQuery("select MAX(billid) as billid from bill");
            if (rs2.next()) {
                billid = rs2.getInt("billid");
            }
            
            
            ResultSet rs3 = DBLoader.executeQuery("select * from billdetail");
            
            for(int i=0;i<al.size();i++)
            {
                rs3.moveToInsertRow();
                
                rs3.updateInt("billid", billid);
                rs3.updateString("pname", al.get(i).productname);
                rs3.updateInt("offerprice", al.get(i).offerprice);
                rs3.updateInt("quantity", al.get(i).quantity);
                
                rs3.insertRow();
            }
            
            JOptionPane.showMessageDialog(this, "Bill generated Successfuly");
                    
                   
                    
            
            
            }
            
            catch(Exception ex){
                ex.printStackTrace();
                
            }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminGetDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminGetDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminGetDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminGetDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminGetDetails(al).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
